#!/bin/sh
. "$(dirname $0)/vars.sh"
[ $# -lt 4 ] && echo "Usage: $(basename $0) <HOST> <DATABASE> <USER> <PASSWORD> [<OUTPUT_DIRECTORY> <ID>]" && exit 1
DATE_TIME=$(date +"%Y%m%d%H%M%S%3N")
HOST=$1
DATABASE=$2
USER=$3
PASSWORD=$4
OUTPUT_DIRECTORY="$5"
ID=$6 
if [ -z "$ID" ]
    then
        ID=$DATE_TIME
fi
COMPRESS_DIRECTORY="$DATABASE-$ID"
[ -n "$OUTPUT_DIRECTORY" ] || OUTPUT_DIRECTORY=.
test -d $OUTPUT_DIRECTORY || $MKDIR -p $OUTPUT_DIRECTORY
[ -n "$COMPRESS_DIRECTORY" ] || COMPRESS_DIRECTORY=.
test -d $COMPRESS_DIRECTORY || $MKDIR -p $COMPRESS_DIRECTORY
$MYSQLDUMP -h $HOST -u $USER -p$PASSWORD $DATABASE > $COMPRESS_DIRECTORY/$DATABASE-$ID.sql
for TABLE in $($MYSQL -NBA -h $HOST -u $USER -p$PASSWORD -D $DATABASE -e 'show tables') 
do
    $MYSQLDUMP --complete-insert --skip-extended-insert -h $HOST -u $USER -p$PASSWORD $DATABASE $TABLE > $COMPRESS_DIRECTORY/$TABLE.sql
done
$TAR cvfz $COMPRESS_DIRECTORY.tar.gz $COMPRESS_DIRECTORY
$RM -r $COMPRESS_DIRECTORY
$MV $COMPRESS_DIRECTORY.tar.gz $OUTPUT_DIRECTORY
echo $OUTPUT_DIRECTORY/$COMPRESS_DIRECTORY.tar.gz
