#node messenger.js "Hola! Este es la pregunta de la semana para Merit Builders. Queremos que usted comunicas la pregunta a todos los empleados. Viernes, o mas temprano por el frio, vamos a eligir un empleado para responder. Si tienes alguna sugerrencia para la pregunta de la proxima semana, por favor mandarlo a joaquin@meritcharge.com, incluyendo la repuesta correcta. Pregunta (Cuales son cinco de las diez razones para remover un Synthetic Web Sling o faja de servicio?) "
#node messenger.js "Hello! This is the question of the week for Merit Builders. We would like you to share it with the other employees. Friday, or sooner because of the cold, we will randomly select an employee to answer. Question: (What are 5 of the 10 reasons for removing Synthetic Webbing Sling from service?) "

#20160122 - Oscar Diaz
# node messanger.js "Hola! Quien contesta la pregunta de la semana es Oscar Hernan Diaz Mendez. Con el telefono de un Supervisor, por favor tomar una foto de el ID Card y mandar lo a 301-514-4956. Mandar un mensaje con la respuesta correcta a 301-514-4956. O, si prefieres, llamar con la repuesta y dejar un mensaje a 301-514-4956. Por favor notificar el hombre contestando la pregunta que puede eligir un sobre de oro. Otravez, la pregunta es: (Cuales son cinco de las diez razones para remover un Synthetic Web Sling o faja de servicio?) " $1
# node messanger.js "Hello! Oscar Diaz is answering the question for the week. With the telephone of a supervisor, please take a picture of his ID Card and send it to 301-514-4956. Send a message with the correct answer to 301-514-4956. Or, if you prefer, call with the answer and leave a message at 301-514-4956. Please notify the responder that an envelope of gold may be selected. Once again, the question is: (What are 5 of the 10 reasons for removing Synthetic Webbing Sling from service?) " $1

#20160128 - Joel Martinez
#node messanger.js "Hola! Quien contesta la pregunta de la semana es Joel Martinez. Este Viernes, con el telefono de un Supervisor, por favor tomar una foto de el ID Card y mandar lo a 301-514-4956. Mandar un mensaje con la respuesta correcta a 301-514-4956. O, si prefieres, llamar con la repuesta y dejar un mensaje a 301-514-4956. Por favor notificar el hombre contestando la pregunta que puede eligir un sobre de oro. Otravez, la pregunta es: (Que son seis cosas que inspecionas antes de usar el man lift) " $1
